# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'About'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- { name: 'About', url: 'about' }
- { name: 'Testimonials', url: 'testimonials' }
- { name: 'My Journey', url: 'journey' }
- { name: 'Contact', url: 'contact' }
# - { name: 'Sample Posts', url: 'sample-posts' }
# - { name: 'Documentation', url: 'documentation' }
# getting-started - Testimonials

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- { icon: 'envelope', link: 'mailto:ayushityagi890@gmail.com' }
- { icon: 'linkedin', link: 'https://www.linkedin.com/in/ayushi-tyagi-089074201/' }
# - {icon: 'twitter', link:    'https://twitter.com/paululele'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Updated on'
